### ISSUE TITLE
翻译README文档/Translate README documents

### ISSUE THREAD

**Issue by adorabled4** [adorabled4/Implementation-of-os-classical-algorithm#2]
### 描述

为了方便更多的人来了解项目，一份便于理解的英文文档是十分必要的，我们需要一位同学来帮助我们**翻译项目的README文档**，同时在README文档中**添加上英文文档的链接**

### 任务

**翻译项目根目录下的README文档，同时在README文档中**添加上英文文档的链接**

### Description
In order to facilitate more people to understand the project, an easy to understand English document is very necessary. We need a classmate to help us  **translate the README document of the project**, and **add a link to the English document in the README document**
### Task
**Translate the README document in the root directory of the project, and add a link to the English document in the README document**

**Comment by Forfernweh** [comment]
Please give me,may be I can't finish it.

**Comment by adorabled4** [comment]
> Please give me,may be I can't finish it.

please try ur best 🥰🥰🥰
